---
AWSTemplateFormatVersion: '2010-09-09'
Description: This is an AWS Cloudformation template that will create the source and targets and accompanying roles to quickly utilize the Healthshare Transformation Service.
Parameters:
  HL7SourceBucketName:
    Description: The source bucket to pull HL7 Messages for Transformation
    Type: String
  HL7SourceBucketKey:
    Description: The key (folder) in the source bucket to pull from. (Enforced)
    Type: String
    Default: in
  FHIRTargetBucketName:
    Description: The target bucket to push the FHIR Resources and Bundles to
    Type: String
  FHIRTargetBucketKey:
    Description: The key (folder) in the source bucket to pull from. (enforced)
    Type: String
    Default: out
  FHIRSourceBucketLoggingKey:
    Description: The key (folder) in the source bucket to log to. (enforced)
    Type: String
    Default: logs
  BucketRegion:
    Description: Where the buckets reside. Note, this must be the same region as your hmts pipeline.
    Type: String
    Default: us-east-2
    AllowedValues:
    - us-east-1
    - us-east-2
    - eu-central-1
    - eu-west-2
    - eu-west-3
  HealthLakeRegion:
    Description: Your AWS Healthlake Region
    Type: String
    Default: us-east-2
    AllowedValues:
    - us-east-1
    - us-east-2
  HealthLakeFHIRDataStoreID:
    Description: Your AWS Healthlake DataStore ID
    Type: String
Mappings:
  AMI2RegionMap:
    eu-west-1:
      '64': ami-1c4a046f
    eu-central-1:
      '64': ami-b03ffedf
Resources:
  HL7SourceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${HL7SourceBucketName}-hmts-source
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
  FHIRTargetBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${FHIRTargetBucketName}-hmts-target
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
  IAMRoleS3toS3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: HMTSBucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListObject
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                Resource: 
                  - !Sub "arn:aws:s3:::${HL7SourceBucketName}"
                  - !Sub "arn:aws:s3:::${HL7SourceBucketName}/*"
                  - !Sub "arn:aws:s3:::${FHIRTargetBucketName}"
                  - !Sub "arn:aws:s3:::${FHIRTargetBucketName}/*"
  IAMRoleS3toHealthLake:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
                - healthlake.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: HMTSBucketHealthlakeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListObject
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                  - healthlake:CreateResource
                  - healthlake:ReadResource
                  - healthlake:DeleteResource
                  - healthlake:SearchWithGet
                  - healthlake:SearchWithPost
                  - healthlake:UpdateResource
                  - healthlake:GetCapabilities
                Resource: 
                  - !Sub "arn:aws:s3:::${HL7SourceBucketName}"
                  - !Sub "arn:aws:s3:::${HL7SourceBucketName}/*"
                  - !Sub "arn:aws:s3:::${FHIRTargetBucketName}"
                  - !Sub "arn:aws:s3:::${FHIRTargetBucketName}/*"
                  - !Sub "arn:aws:healthlake:${AWS::Region}:${AWS::AccountId}:datastore/fhir/${HealthLakeFHIRDataStoreID}"
Outputs:
  HMTSS3toS3RoleArn:
    Description: IAM Role for S3 to S3
    Value:
      Fn::GetAtt:
      - IAMRoleS3toS3
      - Arn
  HMTSFHIRtoS3RoleArn:
    Description: IAM Role for S3 to Healthlake
    Value:
      Fn::GetAtt:
      - IAMRoleS3toHealthLake
      - Arn